pool:
    vmImage: 'ubuntu-latest'

trigger:
  batch: true
  branches:
    include:
      - "*"

workspace:
  clean: all

variables:
  BuildConfiguration: 'Release'
  BuildPlatform: 'Any CPU'

steps:
  - task: NuGetToolInstaller@1
    displayName: 'Use NuGet 6.4.0'
    inputs:
      versionSpec: '6.4.0'

  - task: UseDotNet@2
    displayName: 'Use dotnet 6'
    inputs:
     version: '6.0.x'

  - task: NuGetCommand@2
    displayName: 'Restore Public & Private NuGet Packages'
    inputs:
      command: 'restore'
      restoreSolution: '**/*.sln'
      feedsToUse: 'select'
      vstsFeed: 'c5095ddb-6433-4990-a3a5-1df8a78b1302/$(FeedSecret)'

  - task: DotNetCoreCLI@2
    displayName: 'Build Everything'
    inputs:
      command: 'build'
      projects: 'src/**/*.csproj'
      arguments: '--configuration $(BuildConfiguration) --no-restore'

  - task: DotNetCoreCLI@2
    displayName: 'Run Unit Tests'
    inputs:
      command: test
      projects: 'src/**/*.UnitTests.csproj'
      arguments: '--configuration $(BuildConfiguration) --no-restore'

  - task: DotNetCoreCLI@2
    displayName: 'Publish iStore Adapter'
    inputs:
      command: publish
      publishWebProjects: false
      projects: 'src/Dfe.Spi.IStoreAdapter.FunctionApp/Dfe.Spi.IStoreAdapter.FunctionApp.csproj'
      arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)/publish --no-restore --no-build'

  - task: CopyFiles@2
    displayName: 'Copy ARM template'
    inputs:
      Contents: |
        azure/*
      TargetFolder: '$(Build.ArtifactStagingDirectory)/publish'
      OverWrite: true

  - task: CopyFiles@2
    displayName: 'Copy EAPIM files'
    inputs:
      Contents: |
        eapim/*
      TargetFolder: '$(Build.ArtifactStagingDirectory)/publish'
      OverWrite: true

  - task: PublishBuildArtifacts@1
    displayName: 'Publish All Artifacts'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/publish'